### ISSUE TITLE
Inbox crashes on some devices

### ISSUE THREAD

**Issue by rudchenkos** [Pushwoosh/pushwoosh-inbox-ui-android-sdk#3]
According to our crash reporting, inbox crashes on some user devices (Android 8, 8.1 and 9) of various vendors (SAMSUNG, Huawei, Sony):

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
	at com.pushwoosh.internal.command.b.a(Unknown Source:4)
	at com.pushwoosh.internal.command.CommandApplayer.applyCommand(Unknown Source:36)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:11)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:44)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:43)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:58)
	at com.pushwoosh.inbox.d.h.run(Unknown Source:4)
	at com.pushwoosh.PushwooshService.onHandleWork(Unknown Source:47)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

We cannot reproduce it ourselves, but the volume of the crashes on user devices is significant. This may have something to do with the recent update of the google-services plugin from `3.2.1` to `4.0.2`.

Our current build settings:
```
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31"
        // Do not upgrade to 4.1.0: https://stackoverflow.com/a/52925989/498067
        // With 4.2.0 build fails with java.lang.ArrayIndexOutOfBoundsException
        classpath 'com.google.gms:google-services:4.0.2'
...
compileSdkVersion 'android-28'
targetSdkVersion 28
...
    // On 5.14.2+ Inbox fails with ClassNotFound for PushwooshPlatform
    implementation "com.pushwoosh:pushwoosh:5.14.1"
    implementation "com.pushwoosh:pushwoosh-inbox-ui:5.14.1"
    implementation "com.google.firebase:firebase-core:11.8.0"
    implementation "com.google.firebase:firebase-messaging:11.8.0"
```

**Comment by wfhm** [comment]
Hi @rudchenkos,

Checking it.

**Comment by wfhm** [comment]
@rudchenkos

Fixed with the latest release.

**Comment by rudchenkos** [comment]
Thank you!

**Comment by rudchenkos** [comment]
Thank you, we'll deploy our app with the new version of the SDK and check the effect on crashes 👍

**Comment by wfhm** [comment]
@rudchenkos

Let us know about the result!

**Comment by rudchenkos** [comment]
Hi @wfhm 

The topic crash does not appear anymore, but we've got three new:

1) The worst  (255 instances):
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: cant parse value by key:inbox_params value:{rt=1560504060}
	at com.pushwoosh.internal.utils.JsonUtils.mapToBundle(Unknown Source:173)
	at com.pushwoosh.internal.utils.JsonUtils.jsonStringToBundle(Unknown Source:9)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:44)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:70)
	at com.pushwoosh.inbox.d.g.run(Unknown Source:6)
	at com.pushwoosh.PushwooshService.onHandleWork(Unknown Source:47)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

2) And 33 instances of this:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:355)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/notification/PushBundleDataProvider;
	at com.pushwoosh.inbox.d.a.a(Unknown Source:0)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:48)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:43)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:58)
	at com.pushwoosh.inbox.d.h.run(Unknown Source:4)
	at com.pushwoosh.PushwooshService.onHandleWork(Unknown Source:47)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.notification.PushBundleDataProvider" on path: DexPathList[[zip file "/data/app/nl.albumprinter.smartphone.editor-sP_quF5h0ByGa8CKyVWG1A==/base.apk"],nativeLibraryDirectories=[/data/app/nl.albumprinter.smartphone.editor-sP_quF5h0ByGa8CKyVWG1A==/lib/arm64, /data/app/nl.albumprinter.smartphone.editor-sP_quF5h0ByGa8CKyVWG1A==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 13 more
```

I don't know how these two relate to the original problem. Please dispatch to separate tickets, if needed.

**Comment by wfhm** [comment]
Hi @rudchenkos,

Thanks for the information provided.

Fixed it in the latest release of the Pushwoosh-Android SDK.

https://github.com/Pushwoosh/pushwoosh-android-sdk/releases/tag/5.15.1

Report from your colleague:

https://github.com/Pushwoosh/pushwoosh-inbox-ui-android-sdk/issues/5
