### ISSUE TITLE
Inbox crashes on some devices (5.14.4)

### ISSUE THREAD

**Issue by jimmyjansen93** [Pushwoosh/pushwoosh-inbox-ui-android-sdk#5]
Following up on #3 (made by @rudchenkos who is on holiday) we have some new crashes on the latest release:
The biggest one caused over 1000 crashes in 3 days:
```java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: cant parse value by key:inbox_params value:{rt=1560504060}
	at com.pushwoosh.internal.utils.JsonUtils.mapToBundle(Unknown Source:173)
	at com.pushwoosh.internal.utils.JsonUtils.jsonStringToBundle(Unknown Source:9)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:44)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:70)
	at com.pushwoosh.inbox.d.g.run(Unknown Source:6)
	at com.pushwoosh.PushwooshService.onHandleWork(Unknown Source:47)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

The smaller one caused 49 crashes in the same timeframe:
```java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:355)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/notification/PushBundleDataProvider;
	at com.pushwoosh.inbox.d.a.a(Unknown Source:0)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:48)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:43)
	at com.pushwoosh.inbox.d.a.a(Unknown Source:58)
	at com.pushwoosh.inbox.d.h.run(Unknown Source:4)
	at com.pushwoosh.PushwooshService.onHandleWork(Unknown Source:47)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.notification.PushBundleDataProvider" on path: DexPathList[[zip file "/data/app/nl.albumprinter.smartphone.editor-sP_quF5h0ByGa8CKyVWG1A==/base.apk"],nativeLibraryDirectories=[/data/app/nl.albumprinter.smartphone.editor-sP_quF5h0ByGa8CKyVWG1A==/lib/arm64, /data/app/nl.albumprinter.smartphone.editor-sP_quF5h0ByGa8CKyVWG1A==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 13 more
```

This has happened on android 8, 8.1 and 9  according to our crash reporting. 

Any help would be greatly appreciated!

**Comment by wfhm** [comment]
Hello @jimmyjansen93,

Checking it!

**Comment by wfhm** [comment]
Hi @jimmyjansen93,

just fixed it in the latest release of the Pushwoosh-Android SDK. Please update it in your application.

https://github.com/Pushwoosh/pushwoosh-android-sdk/releases/tag/5.15.1

**Comment by jimmyjansen93** [comment]
Thanks, making a build now and will release today. Will report back tomorrow 👍

**Comment by jimmyjansen93** [comment]
Seems like it is fixed! thanks a lot!

**Comment by wfhm** [comment]
@jimmyjansen93,

You are welcome, thanks for the feedback provided!
