### ISSUE TITLE
A lot of crashes

### ISSUE THREAD

**Issue by dimawushu** [Pushwoosh/pushwoosh-inbox-ui-android-sdk#7]
Till 03.02.2022 there are lot of crashes in android app calling by pushwoosh.

Can you help?

versions i guess 6.4.1

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:415)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
       
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
       at com.pushwoosh.repository.y.a(:27)
       at com.pushwoosh.repository.RepositoryModule$a.a(:12)
       at com.pushwoosh.repository.RepositoryModule$a.doInBackground(:2)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(Th
<img width="1335" alt="Снимок экрана 2022-02-11 в 17 52 24" src="https://user-images.githubusercontent.com/16700777/153624175-67b5a757-f946-4756-a47d-e31e5a28d86c.png">
readPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by wfhm** [comment]
@dimawushu It most likely comes from the 6.4.0 version - this is a known issue, and it was fixed with 6.4.1. Did your previous release include the 6.4.0 version of Pushwoosh SDK?

**Comment by dimawushu** [comment]
I guess yes, now it is 6.4.0,
I will update to the newest one (6.4.1) and will watch.

**Comment by wfhm** [comment]
@dimawushu The issue should already be fixed, and it is actually unrelated to this repo (it happens in the core module, and this is a repo of the Inbox UI component), so I am closing the issue for now, however, please feel free to reopen it if the issue persists with the latest version.
